name: PollQuest Workflow
'on':
  push:
    branches:
      - master
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test
        run: mvn test

  dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t pollquest-service .

      - name: Tag Docker image
        run: docker tag pollquest-service salilsri19/pollquest-service:latest

      - name: Log in to Docker registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to registry
        run: docker push salilsri19/pollquest-service:latest
